# Generated by Django 5.2 on 2025-05-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('full_name_customer', models.CharField(max_length=100)),
                ('phone_customer', models.CharField(max_length=20, unique=True)),
                ('email_customer', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_drive', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('document_driver', models.CharField(max_length=20)),
                ('full_name_driver', models.CharField(max_length=50)),
                ('email_driver', models.EmailField(max_length=254, unique=True)),
                ('phone_driver', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id_route', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('origin_name', models.CharField(max_length=100)),
                ('origin_point', models.CharField(max_length=100)),
                ('destination_name', models.CharField(max_length=100)),
                ('destinantion_point', models.CharField(max_length=100)),
                ('distancia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_vehicle', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('id_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DriveMe.customer')),
                ('id_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DriveMe.driver')),
                ('id_route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DriveMe.route')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=6, unique=True)),
                ('model', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=4)),
                ('soat_expiration', models.DateField(blank=True, null=True)),
                ('tecnico_mecanica_expiration', models.DateField(blank=True, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DriveMe.driver')),
                ('type_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DriveMe.typeofvehicle')),
            ],
        ),
    ]
