# Generated by Django 5.2 on 2025-05-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveMe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofvehicle',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AddField(
            model_name='typeofvehicle',
            name='id_type_vehicle',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
